### ISSUE TITLE
$cordovaNgCardIOProvider is not defined

### ISSUE THREAD

**Issue by Vincenttbk** [daruwanov/angular-cordova-cardio#2]
Hi,

I've added the plugin, but when I'm trying to call the CardIO function, i encountered the error following error:
 $cordovaNgCardIOProvider is not defined

Any help will be appreciated.
Thank you :)

**Comment by daruwanov** [comment]
Hello. 
Did you added cordova card io cordova plugin?
Did you added this library to you project? 
Did you include ngCardIO.js to your index.html and inject ngCardIO to your angular module?

**Comment by daruwanov** [comment]
By the way.. I will check this this tomorrow and give you feedback.
